### ISSUE TITLE
Build fail while resolve dependency

### ISSUE THREAD

**Issue by karma-sun** [notea-org/notea#161]
seems that dependency @headwayapp/react-widget require react^16.8.0,but notea require react^17.0.2

2023-01-06 11:14:06: npm
2023-01-06 11:14:06:  ERR! code ERESOLVE
2023-01-06 11:14:06: npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: notea@0.4.0-alpha
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @headwayapp/react-widget@0.0.4
npm ERR! node_modules/@headwayapp/react-widget
npm ERR!   @headwayapp/react-widget@"^0.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /tmp/karma-sun-notea/.npm/eresolve-report.txt for a full report.

**Comment by tecc** [comment]
Might have to fork [headwayappco/widget](https://github.com/headwayappco/widget) since they haven't maintained it whatsoever (last commit was 1½ years ago).

**Comment by tecc** [comment]
Try the new branch, [fix/161-headway-fail](https://github.com/notea-org/notea/tree/fix/161-headway-fail). I've also created a pull request for this issue (#163).

**Comment by karma-sun** [comment]
> Try the new branch, [fix/161-headway-fail](https://github.com/notea-org/notea/tree/fix/161-headway-fail). I've also created a pull request for this issue (#163).

good,it works
