### ISSUE TITLE
Better ultrawide support

### ISSUE THREAD

**Issue by Tirarex** [notea-org/notea#167]
Everything works fine but not as convenient as you want.
My monitor has a resolution of 3440x1440 pixels and a real size of 34 inches. The elements on the site are quite small, the text area is very small, the left panel takes up a lot of space in its normal state and is far to the left if it collapsed.

 
![image](https://user-images.githubusercontent.com/20671593/221397818-4af3d771-34e3-48e0-a111-ed0ab28f67f3.png)

And same content in Retype wiki.
![image](https://user-images.githubusercontent.com/20671593/221397825-bc564a3e-41e7-4f3b-aae6-4bdf8b83068e.png)

**Comment by tecc** [comment]
I created a fix for this on the [fix/167-wider-screens](https://github.com/notea-org/notea/tree/fix/167-wider-screens) branch.

**Comment by Tirarex** [comment]
> I created a fix for this on the [fix/167-wider-screens](https://github.com/notea-org/notea/tree/fix/167-wider-screens) branch. Feel free to try it and say if it needs more adjustment.
> 
> To switch to the new mode, click the `Toggle width` button.

Sorry but i have 0 idea how to run it. 
I cloned repo with branch and did comand from readme, this is what i get:

`
PS D:\notea> docker-compose up -d
[+] Running 2/2
 - Network notea_default    Created                                                                                0.0s
 - Container notea-minio-1  Started                                                                                0.6s

PS D:\notea> yarn dev
yarn run v1.22.19
$ next
'next' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
`

**Comment by tecc** [comment]
My guess is that the packages aren't installed yet. Could you try running `yarn`?

**Comment by Tirarex** [comment]
yarn is installed (v1.22.19) i running it on docker desktop ( windows 11 wsl enabled, ryzen 9 5950x, 64gb ram)

**Comment by tecc** [comment]
To clarify, I mean you should run the following command:
```bash
yarn
```

The `yarn` command by itself installs the dependencies of the project, which may take a while.
Why I'm asking you to do that is because the error looks to be that you don't have the project dependencies installed.

**Comment by tecc** [comment]
Just to simplify the process, this is what it looks like for me (I have it zoomed out though, just to make it look larger):
![image](https://user-images.githubusercontent.com/38840234/224521561-4d6ef10d-e10e-49cb-87f1-84ea342071aa.png)

**Comment by Tirarex** [comment]
Looks nice to me ! i will wait docker image update!

**Comment by tecc** [comment]
Just as a bonus, I'm also going to replace the toggle system with a dedicated menu.
![image](https://user-images.githubusercontent.com/38840234/224533644-6a275d4f-3bf0-456c-85e2-0a2960021883.png)
![image](https://user-images.githubusercontent.com/38840234/224533616-31c7cfa1-77a1-446d-9b79-7296dfede30d.png)

**Comment by Tirarex** [comment]
Very nice options for any monitor! 

i tried to start container again, after installing packages via Yarn, notea started. It's take some time to find default password that "123", why not "notea" ? 

Anyway. Loks good to me! 
![image](https://user-images.githubusercontent.com/20671593/224538745-951f89ce-db6d-435b-815c-5b7760a84b60.png)

**Comment by sam5558** [comment]
Hello,
Thank you for creating this Notea project. I really love it as my everyday note taking app.
I had pretty much the same issue/annoyance with the solution not taking as much as possible as the available display.

Is there an ETA for this feature on the latest docker release ?  Just so i know if it is implemented or not yet.

Regards

**Comment by tecc** [comment]
I have no idea when this will be pushed to the stable main branch (I've a *lot* of work to do until I'm happy to call it entirely stable).
Until then, if you'd like to use this feature, you can use the `edge` tag instead of the `latest` tag. Any image pushed to the edge tag will contain features pretty much as soon as they're implemented, at the cost of potential stability.

**Comment by sam5558** [comment]
Thank you for your reply.

I'll try my luck with the edge tag and see if it is stable for my daily use.

**Comment by Tirarex** [comment]
I build docker image of  [fix/167-wider-screens](https://github.com/notea-org/notea/tree/fix/167-wider-screens) and deployed to main docker server. ( always make backups!), it work only couple of days without any problems
