### ISSUE TITLE
Helm Chart for Kubernetes

### ISSUE THREAD

**Issue by KirillDemtchenko** [notea-org/notea#172]

**Comment by tecc** [comment]
Could you elaborate more on this issue? You haven't provided a description and as such I don't know what this issue is really about (beyond helm charts and Kubernetes, of which I have experience with neither).

**Comment by KirillDemtchenko** [comment]
Hello, @tecc!

Yes, it's about creating Helm Chart for deploying notea to Kubernetes. Helm Chart is like a package manager, but for Kubernetes : ) And, I can do this issue, because I already simple chart for deploying in my Kubernetes.

**Comment by tecc** [comment]
Alrighty then! Feel free to PR whenever you want to. Contributions are always appreciated ;)
