### ISSUE TITLE
Bucket Access with IAM role

### ISSUE THREAD

**Issue by damc-dev** [notea-org/notea#95]
Best practice is to use IAM role provided for S3 client access instead of providing access and secret keys.
Since S3 client instantiation provides explicit access and secret keys it takes precedence over IAM Role.
Should be fixable by not passing in the access and secret keys if environment variable is not set.

**Comment by QingWei-Li** [comment]
Can you tell me exactly what to do, sorry I don’t understand IAM.

**Comment by okdas** [comment]
@QingWei-Li I believe @damc-dev refers to how AWS API keys are getting populated. In AWS world, it is not necessary to provide AWS keys, but AWS SDK will pick up the role/instance profile/EKS-IRSA automatically. https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-node#aws-credential-provider-for-nodejs

I have not tested how notea behaves in this scenario. :)

**Comment by dcampoyil** [comment]
@QingWei-Li I can see this project is using already the aws-sdk as S3 client. I believe that if you make STORE_ACCESS_KEY and STORE_SECRET_KEY optional and don't add the [credentials field](https://github.com/QingWei-Li/notea/blob/ba1987c7e4ac1741eb2d576bdad9b8de183409b9/libs/server/store/providers/s3.ts#L43) when there are undefined, then aws-sdk will be able to pick the AWS credentials up from the role/instance profile/EKS-IRSA automatically.

Happy to help with code or testing if you want.

**Comment by QingWei-Li** [comment]
@dcampoyil Thanks! It would be better if you could help, I'm sorry I don't have time to study this yet
